### PR TITLE
bl-exit: add configuration via config for LOCK_SCREEN_COMMAND

### PR DESCRIPTION
**Pull request by 01micko**
Specifically, I needed this for labwc which use 'swaylock'

I need this:

```
swaylock -F -f --indicator-idle-visible  -i $HOME/Pictures/wallpapers/bunsen/default/default
```

Feel free to edit as necessary.

### CODE REVIEW

**Comment by johnraff** [comment]
Thanks for your contribution. Allowing users to configure their choice of screenlock command looks like a worthwhile improvement.

I'm wondering, though, whether we ought to integrate this with the BunsenLabs utility [bl-lock](https://github.com/BunsenLabs/bunsen-utilities/blob/boron/bin/bl-lock)

Having two separate places to configure screen-locking might be confusing. Perhaps one of bl-exit or bl-lock ought to call the other for screen locking? Then configuration can go in one place. It would, however introduce an extra dependency.

**Comment by 01micko** [comment]
> I'm wondering, though, whether we ought to integrate this with the BunsenLabs utility bl-lock

Probably so.

Thanks for review.

So does `$HOME/.config/bunsen/bl-lock`get created when first booted installed? Anyway that doesn't really matter but as far as I can tell `light-locker-command -l` is hard coded in `bl-lock` script and screen locking in `bl-exit` seems independent of it anyway.

`bl-lock` wasn't on the list [here](https://forums.bunsenlabs.org/viewtopic.php?pid=133969#p133969)

I'll have a think about the best approach.

**Comment by 01micko** [comment]
I think I might change the path of the config to `$HOME/.config/bunsen/bl-lock`. That way it won't _depend_ on `bunsen-lock` at all because it is a file that will only be shipped when a wayland compositor is included.

There is also a little bug I need to fix for `yad`.  In the `yad --help-gtk` there is the `--name` option which seems as a requirement for wayland to show the correct  icon in the taskbar. It's similar to setting `app_id`. So the `--name` is the same as `--window-icon`.

**Comment by 01micko** [comment]
Updated with changes from the above post, also checking that `$HOME/.config/bunsen/bl-lock` is not empty.

**Comment by johnraff** [comment]
There is no package bunsen-lock. bl-lock is a script which is included in [bunsen-utilities](https://github.com/BunsenLabs/bunsen-utilities) which was on my first draught list for a "base" install, but which I'm now thinking of leaving out.

btw, naming: BunsenLabs _packages_ are all named **bunsen-something**, while _commands_ which BL provides are named **bl-something**, to keep the namespace of executables in /usr/bin/ free of possible clashes with commands provided by unrelated packages.

The long-standing dissatisfaction I've had is that multiple lock commands are used, depending on whether the user invokes `bl-exit --lock` or `bl-lock`. (As you say, bl-exit does not use light-locker.) I think they should be unified so the user doesn't have to configure two separate utilities. Another issue that will need looking at is xfce4-power-management's invoking of light-locker, which we wouldn't like to break. Does light-locker work on Wayland? If not, then disconnection of our screenlock utilities from light-locker is an optional configuration that wayland users will need.

> does $HOME/.config/bunsen/bl-lock get created when first booted installed?

No.

> I think I might change the path of the config to $HOME/.config/bunsen/bl-lock. 

That will be appropriate if bl-exit's lock function were to depend on bl-lock. But bl-lock is only present if bunsen-utilities has been installed. 

Right now I'm thinking it might be simpler if bl-lock were to invoke `bl-exit --lock` by default. That way bunsen-exit would not need to depend on the much bigger bunsen-utilities, but for bunsen-utilities to depend on bunsen-exit would not be a major issue. But then bl-exit's default (but user-configurable) lock command would need to be `light-locker-command -l` so as not to break xfce4-power-manager integration.

So it's all a bit tricky.

**Comment by johnraff** [comment]
Re: debian/changelog
This file is normally edited by the package maintainer (me in this case) and brings a new version number. You were correct to bump to 13 for Carbon, if your intention was for these changes to be used with Debian Trixie, but when the packages migrate to Carbon there are some other changes I would also like to add, such as bumping the debhelper and Debian standards versions, as I did when migrating to Boron: https://github.com/BunsenLabs/bunsen-exit/blob/6f992c7ab96bd7f1904b75032591c65087ad59c2/debian/changelog#L23
```
bunsen-exit (12.0-1) boron; urgency=medium

  * Update debian/control:
    - Standards version to 4.6.1.0
    - Debhelper compatibility to 13
    - Add Rules-Requires-Root: no
    - Replace Depends: policykit-1 with polkitd, polkitd-pkla

  * Update debian/copyright:
    - Update year
    - Format: use https url

  * Update debian/genman.sh to ver 20220126

 -- John Crawley <john@bunsenlabs.org>  Sat, 21 Jan 2023 16:07:49 +0900
```

NMU (non-maintainer uploads) are possible though, if a comment is added to the changelog, as another developer did here: https://github.com/BunsenLabs/bunsen-exit/blob/6f992c7ab96bd7f1904b75032591c65087ad59c2/debian/changelog#L244
```
bunsen-utilities (8.6.1-1) bunsen-hydrogen; urgency=medium

  * Non-maintainer upload.
  * New upstream version.
```
  
Can we get the Carbon migration done first, then add your changes as an NMU? (That will also allow some time to think about all the above issues.)

**Comment by 01micko** [comment]
>  Does light-locker work on Wayland? If not, then disconnection of our screenlock utilities from light-locker is an optional configuration that wayland users will need.

It doesn't. All the utilities to lock screen on wl-roots based wayland (`labwc`, `sway`, `hyprland`, `wayfire`, being the most popular ones) depend on wl-roots protocols. 

What does work on wayland is anything gtk3 or 4 based (some need work arounds, not much though), SDL2 based, most things qt5 or 6 based and many older X and gtk2 apps with Xwayland. Anything lower level in the graphics stack, such as output power management, idle daemons and the like that work for X don't work in wayland. 

I'll close this PR as it's not urgent and it will give you time to decide which way to go with bl-exit <> bl-lock.

I'm working on other related things anyway and will start a git repo that you can take over when it's ready (bunsen-wayland or something) with config files for `skel`  and various little scripts which I'll prefix 'blw-'

Another headache is wallpaper setting! I have a little yad script for now which I'll upload to said repo. I'm going to have to migrate from my VM to bare metal soon as you can't test everything in a VM but it's a great plcae to start :)

Cheers.

**Comment by johnraff** [comment]
Many thanks for all your help!

> There is also a little bug I need to fix for yad. In the yad --help-gtk there is the --name option which seems as a requirement for wayland to show the correct icon in the taskbar. It's similar to setting app_id. So the --name is the same as --window-icon.

This looks like something that will need doing for all invokations of yad, right? Can --name be added in all cases, also using X, without issues? If so we can add it to the functions in [yad-includes](https://github.com/BunsenLabs/bunsen-common/blob/boron/yad-includes) in bunsen-common right away.

**Comment by 01micko** [comment]
> Many thanks for all your help!
> 
> > There is also a little bug I need to fix for yad. In the yad --help-gtk there is the --name option which seems as a requirement for wayland to show the correct icon in the taskbar. It's similar to setting app_id. So the --name is the same as --window-icon.
> 
> This looks like something that will need doing for all invokations of yad, right? Can --name be added in all cases, also using X, without issues? If so we can add it to the functions in [yad-includes](https://github.com/BunsenLabs/bunsen-common/blob/boron/yad-includes) in bunsen-common right away.

Yes, anything that may need to be used in wayland anyway.

`--name=some-icon` can be added in normal X sessions without consequence __with__ --window-icon=`some-icon`. The `--name` on its own _may_ work in X depending on the window manager, but safer to just have both.
```
yad --help-gtk
Usage:
  yad [OPTION…] - Yet another dialoging program

GTK+ Options
  --class=CLASS                                  Program class as used by the window manager
  --name=NAME                                    Program name as used by the window manager
  --display=DISPLAY                              X display to use
  --gdk-debug=FLAGS                              GDK debugging flags to set
  --gdk-no-debug=FLAGS                           GDK debugging flags to unset
  --gtk-module=MODULES                           Load additional GTK+ modules
  --g-fatal-warnings                             Make all warnings fatal
  --gtk-debug=FLAGS                              GTK+ debugging flags to set
  --gtk-no-debug=FLAGS                           GTK+ debugging flags to unset
```

**Comment by johnraff** [comment]
> `--name=some-icon` can be added in normal X sessions without consequence **with** --window-icon=`some-icon`. The `--name` on its own _may_ work in X depending on the window manager, but safer to just have both.
> 

OK since BeakerLand (BL/Wayland) development won't start till Carbon, let's update yad-includes in bunsen-common / Carbon.

**Comment by johnraff** [comment]
I was wrong here:
>  bl-exit does not use light-locker

In fact, when it calls `loginctl lock-session` with light-locker's daemon running, bl-exit is using light-locker. loginctl itself doesn't lock anything, it just sends out a message. 

Would loginctl call swaylock instead of light-locker if it was called on a system where swaylock was running? That would avoid having to configure bl-exit to call swaylock directly.

**Comment by 01micko** [comment]
> Would loginctl call swaylock instead of light-locker if it was called on a system where swaylock was running? That would avoid having to configure bl-exit to call swaylock directly.

I'm not sure, but I *think* this can be controlled by `swayidle`. Need to do more research on this.

**Comment by 01micko** [comment]
Ok, there is a wayland utility, `wlogout`, designed for wayland and works in BL. This might be the answer because it requires zero configuration on the user side, although I need to test it out on bare metal for suspend and hibernate. Lock, logout, shutdown and reboot work OOTB. One issue - seems no `.desktop` file because no menu entry. Easy fix though I guess with a wrapper. You can then leave bl-exit and bl-lock alone :)

**Comment by johnraff** [comment]
Discussion continued here: https://forums.bunsenlabs.org/viewtopic.php?id=9515
I've committed a revised bl-exit and bl-exit.conf  here but that's not the final word on the subject, although it seems to work OK.

(We might get a more elegant solution using the xss-lock daemon.)

**Pull request closed without merging**
